name: coverage

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup/
        with:
          python-version: "3.10"
          optional-dependencies: "development"

      - name: Run tests and collect coverage
        run: pytest --cov --cov-report=xml

      - name: Enforce Patch Coverage
        run: diff-cover coverage.xml --compare-branch=origin/${{ github.base_ref || 'dev' }}
