name: pylint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    strategy:
      matrix:
        python-version: [ "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          optional-dependencies: "development"
      - name: lint
        run: pylint --rcfile=.pylintrc --fail-under=9.5 --fail-on=E,F src/build123d
