name: Wheel building and publishing

on: [push, pull_request, workflow_dispatch] # TODO: update this later

permissions: {}

jobs:
  build_wheel:
    # This does the actual wheel building or if triggered manually via the workflow dispatch, or for a tag.
    # this job does NOT publish the wheel
    name: Build wheel on ubuntu-latest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    if: (github.repository == 'gumyr/build123d' && ( startsWith(github.ref, 'refs/tags/v'))) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0 # get all history for setuptools_scm
        
      - name: Build sdist and wheel (main build123d)
        shell: bash
        run: |
          pwd
          ls -lR
          python3 -V
          python3 -m pip install --upgrade pip
          python3 -m pip -V
          python3 -m pip install build
          python3 -m build --outdir wheelhouse
          python3 -m pip freeze
          ls -lR

      - name: Build sdist and wheel (build123d-vtk)
        shell: bash
        run: |
          WHEEL_FILE=$(ls wheelhouse/build123d-*.whl | head -n 1)

          # Use unzip to stream the METADATA file, then grep the Version line
          CLEAN_VERSION=$(unzip -p "$WHEEL_FILE" "*.dist-info/METADATA" | grep "^Version: " | cut -d' ' -f2)

          # Force setuptools_scm to use this exact version
          export SETUPTOOLS_SCM_PRETEND_VERSION="$CLEAN_VERSION"
          echo "Pretending version for VTK build: $CLEAN_VERSION"

          # Patch pyproject.toml for the VTK variant
          sed -i 's/name = "build123d"/name = "build123d-vtk"/' pyproject.toml
          sed -i 's/cadquery-ocp-novtk/cadquery-ocp/' pyproject.toml

          # Build the new variant into the existing wheelhouse dir
          python3 -m build --outdir wheelhouse

          ls -lR wheelhouse

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          path: ./wheelhouse/*.* # store the build123d wheel and sdist and build123d-vtk variant
      
  upload_pypi:
    needs: [build_wheel]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/build123d
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    # or, alternatively, upload to PyPI on every tag starting with 'v' (remove on: release above to use this)
    if: needs.build_wheel.result == 'success'
    #if: (github.repository == 'gumyr/build123d' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 #v7.0.0
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b #v1.14.0
        # with: # for testing with test.pypi.org
          # To test: repository-url: https://test.pypi.org/legacy/
