name: Run type checking

on: [push, pull_request]
jobs:
  typecheck:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          "3.14",
          ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          optional-dependencies: "development,stubs"

      - name: Typecheck (mypy)
        run: |
          mypy --config-file mypy.ini src/build123d

      - name: Typecheck (ty)
        run: |
          uv tool install ty@latest
          ty check src/build123d/
        continue-on-error: true
