name: Run type checking

on: [push, pull_request]

permissions:
  contents: read

jobs:
  typecheck:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          "3.14",
          ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          optional-dependencies: "development,stubs"

      - name: Typecheck (mypy)
        run: |
          mypy --config-file mypy.ini src/build123d

      - name: Typecheck (ty)
        run: |
          uv tool install ty@latest
          ty check src/build123d/
        continue-on-error: true
